version: '3'

services:
  postgresql:
    image: postgres
    container_name: nest-pr
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=nest-pr
      - POSTGRES_PASSWORD=nest
      - POSTGRES_DATABASE=nest-pr
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-nest-pr
    ports:
      - '6379-6379'