export const users = [
  {
    _id: '63e15207c411919548eb7549',
    index: 0,
    guid: 'ab345fac-d54a-4e04-924a-6b8d6c9ab0ff',
    isActive: true,
    balance: '$2,668.29',
    picture: 'http://placehold.it/32x32',
    age: 22,
    eyeColor: 'green',
    name: 'Burch Kirby',
    gender: 'male',
    company: 'MOTOVATE',
    email: 'burchkirby@motovate.com',
    phone: '+1 (861) 507-3072',
    address: '980 Gain Court, Wyano, Missouri, 5029',
    about:
      'Amet anim amet officia voluptate sunt nostrud minim minim commodo elit non aliqua incididunt. Sit sunt ex fugiat in. Cupidatat sit enim velit occaecat in reprehenderit do voluptate nisi fugiat incididunt ut nostrud anim. Pariatur reprehenderit deserunt mollit exercitation quis. Labore ex excepteur culpa cillum do id et excepteur non reprehenderit. Incididunt do dolor sint amet do Lorem sint deserunt officia dolore ut ullamco labore. Magna esse do ut officia sint enim id ut aliqua laborum exercitation velit.\r\n',
    registered: '2020-09-14T10:31:52 -03:00',
    latitude: -55.048318,
    longitude: 138.405781,
    tags: ['do', 'culpa', 'dolor', 'sunt', 'duis', 'cupidatat', 'culpa'],
    friends: [
      {
        id: 0,
        name: 'Myers Brown',
      },
      {
        id: 1,
        name: 'Rutledge Underwood',
      },
      {
        id: 2,
        name: 'Fletcher Ortega',
      },
    ],
    greeting: 'Hello, Burch Kirby! You have 1 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '63e152071eaf6efd26163162',
    index: 1,
    guid: '9470d012-c090-457d-84a5-9f2dff0c8dab',
    isActive: false,
    balance: '$2,134.23',
    picture: 'http://placehold.it/32x32',
    age: 30,
    eyeColor: 'green',
    name: 'Greer Vega',
    gender: 'male',
    company: 'ZEROLOGY',
    email: 'greervega@zerology.com',
    phone: '+1 (961) 519-2210',
    address: '548 Jamison Lane, Concho, Guam, 2582',
    about:
      'Duis qui amet labore mollit aliqua deserunt adipisicing consequat duis aliqua deserunt in amet ea. Eu minim cillum quis reprehenderit pariatur laborum adipisicing consequat aliquip tempor ad eu deserunt. In reprehenderit excepteur nostrud dolor dolor anim sunt do eiusmod adipisicing anim non occaecat. Et et enim voluptate deserunt do duis sunt ipsum amet adipisicing nostrud consectetur elit nostrud. Qui culpa ut ad sit mollit deserunt irure ea. Velit sint occaecat laborum non proident Lorem sunt esse nisi. Lorem esse non ut minim nulla consequat dolor magna sunt non.\r\n',
    registered: '2017-02-28T02:46:36 -02:00',
    latitude: -19.541748,
    longitude: -21.365306,
    tags: ['enim', 'enim', 'nisi', 'ea', 'occaecat', 'cupidatat', 'ea'],
    friends: [
      {
        id: 0,
        name: 'Dina Moss',
      },
      {
        id: 1,
        name: 'Gabrielle Hatfield',
      },
      {
        id: 2,
        name: 'Patrice Wilkins',
      },
    ],
    greeting: 'Hello, Greer Vega! You have 3 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '63e152073c1d278493ee8f3a',
    index: 2,
    guid: 'fa3d416a-7d16-40e8-b0c1-9621c2565114',
    isActive: false,
    balance: '$3,271.41',
    picture: 'http://placehold.it/32x32',
    age: 39,
    eyeColor: 'green',
    name: 'Viola Padilla',
    gender: 'female',
    company: 'ACCUSAGE',
    email: 'violapadilla@accusage.com',
    phone: '+1 (925) 568-3253',
    address: '505 Opal Court, Castleton, Virginia, 6341',
    about:
      'Amet duis sint fugiat eu aliqua irure deserunt cupidatat. Enim ea labore excepteur non labore consequat. Elit fugiat elit irure est laboris in mollit et ad esse amet amet fugiat.\r\n',
    registered: '2021-10-10T02:26:22 -03:00',
    latitude: -59.287237,
    longitude: 150.602264,
    tags: ['tempor', 'deserunt', 'occaecat', 'non', 'sit', 'minim', 'tempor'],
    friends: [
      {
        id: 0,
        name: 'Rose Goodwin',
      },
      {
        id: 1,
        name: 'Goldie Forbes',
      },
      {
        id: 2,
        name: 'Britney Gallegos',
      },
    ],
    greeting: 'Hello, Viola Padilla! You have 10 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '63e1520721612d2aa0bba4f5',
    index: 3,
    guid: 'a8cc406e-e9a0-43dc-9745-3a9d6c635b22',
    isActive: true,
    balance: '$2,429.24',
    picture: 'http://placehold.it/32x32',
    age: 31,
    eyeColor: 'blue',
    name: 'Rosalinda Thompson',
    gender: 'female',
    company: 'FITCORE',
    email: 'rosalindathompson@fitcore.com',
    phone: '+1 (937) 470-3994',
    address: '457 Grand Street, Salvo, Washington, 1689',
    about:
      'Incididunt quis dolore in fugiat aliqua cillum. Labore laboris et consectetur ullamco velit nisi dolor commodo veniam qui officia dolore nisi esse. Aute id eiusmod officia laborum officia. Quis nulla ut sunt amet aute. Esse ea consectetur sit ut duis incididunt eiusmod consectetur incididunt laborum aliqua non.\r\n',
    registered: '2016-02-27T08:42:15 -02:00',
    latitude: -12.944194,
    longitude: 85.485861,
    tags: ['magna', 'do', 'adipisicing', 'Lorem', 'commodo', 'veniam', 'in'],
    friends: [
      {
        id: 0,
        name: 'Mccray Aguirre',
      },
      {
        id: 1,
        name: 'Anita Dale',
      },
      {
        id: 2,
        name: 'Abigail Stokes',
      },
    ],
    greeting: 'Hello, Rosalinda Thompson! You have 6 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '63e15207d9cc3ec2e012aa60',
    index: 4,
    guid: 'e0be75df-0efc-4811-adc3-28a74a81c7cd',
    isActive: true,
    balance: '$2,923.88',
    picture: 'http://placehold.it/32x32',
    age: 33,
    eyeColor: 'brown',
    name: 'Herman Barker',
    gender: 'male',
    company: 'ASSURITY',
    email: 'hermanbarker@assurity.com',
    phone: '+1 (801) 443-2776',
    address: '921 Howard Alley, Maplewood, Nevada, 587',
    about:
      'Occaecat ut dolor quis sint et exercitation consequat laborum laborum minim anim mollit. Elit laborum id ipsum enim incididunt sit est veniam incididunt. Tempor esse qui consequat cillum incididunt do reprehenderit non duis ut. Ipsum nostrud nulla culpa qui minim ad culpa eu excepteur adipisicing nulla ea. Occaecat adipisicing nisi sint aliqua aliquip cillum magna deserunt. Exercitation elit incididunt ipsum cupidatat elit dolore sunt officia ad enim esse occaecat elit in. Labore enim mollit amet ex non labore sunt.\r\n',
    registered: '2022-03-05T04:17:23 -02:00',
    latitude: 53.13593,
    longitude: 23.705824,
    tags: ['ex', 'ex', 'aute', 'consectetur', 'tempor', 'non', 'proident'],
    friends: [
      {
        id: 0,
        name: 'Waller Wilkinson',
      },
      {
        id: 1,
        name: 'Magdalena Gates',
      },
      {
        id: 2,
        name: 'Stacy Clark',
      },
    ],
    greeting: 'Hello, Herman Barker! You have 7 unread messages.',
    favoriteFruit: 'strawberry',
  },
];
